version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: social_media_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    container_name: rails-api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/social_media_dev
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
    command: bash -c "bundle install && rails db:migrate && rails server -b 0.0.0.0 -p 3001"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: nextjs-client
    depends_on:
      - server
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      NEXT_PUBLIC_API_URL: http://server:3001

volumes:
  postgres_data:
